eventabase/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from allauth.account import views

urlpatterns = [
    path('', include('landing_page.urls')),
    path('accounts/', include('allauth.urls')),
    re_path(r"^accounts/password/reset/key/(?P<uidb36>.+)-(?P<key>.+)/$",
            views.password_reset_from_key,
            name="account_reset_password_from_key"),
    path('home/', include('home.urls')),
    path('events_and_activities/', include('events_and_activities.urls')),
    path('admin/', admin.site.urls)
]

home/urls.py
from django.urls import path
from events_and_activities.views import PostEventsView, UpdateEventsView, ViewEventsView
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.UserHomePage.as_view(extra_context={'page_id': 'home_page',
                                                       'logged_in': True}),
         name='user_homepage'),
    path('profile_form/', views.ProfileFormView.as_view(),
         name='profile_form_view'),
    path('post_events/', PostEventsView.as_view(), name='post_events_view'),
    path('update_events/', UpdateEventsView.as_view(), name='update_events_view'),
    path('event_withdrawal/', ViewEventsView.as_view(), name='view_events_view')
]

landing_page/urls.py
from django.urls import path
from . import views

app_name = 'landing_page'
urlpatterns = [
    path('', views.LandingPage.as_view(extra_context={'slogan': 'Events & Activities Organised by You for You',
                                                      'page_id': 'landing_page',
                                                      'logged_in': False}), name='landing_page_url'),
    path('terms_and_policies/', views.TermsPoliciesView.as_view(extra_context={'page_id': 'T_and_c'}), name='terms_view')
]

templates/429.html
{% extends "base.html" %}
{% block title %}Request Rate exceeded{% endblock %}
{% block h1 %}Request Rate exceeded{% endblock %}

{% block main %}
<h1>Too Many Requests</h1>

<p>You are sending too many requests. Wait a while and try your desired request again.</p>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block extra_meta %}{% endblock %}
    {% load static %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body {% if page_id %}id="{{page_id}}"{% endif %}>
    <header>
        <h1>{% block h1 %}main heading{% endblock %}</h1>
        {% if slogan %}
            <h2>{{slogan}}</h2>
        {% endif %}
        {% if username %}
        <span>{{username}}</span>
        {% endif %}
        <nav>
            <div>
                {% if logged_in %}
                    {% url "home:user_homepage" as home_url %}
                {% else %}
                    {% url "landing_page:landing_page_url" as home_url %}
                {% endif %}
                <a href="{{ home_url }}" type="text/html" aria-label="Home">
                    <div>
                        <i class="fa-solid fa-house nav_icon"></i>
                        <div class="nav_icon">
                            Home
                        </div>
                    </div>
                </a>
            </div>
            {% if not logged_in %}
                <div>
                    <a href="{% url 'account_login' %}" type="text/html" aria-label="sign-in">
                        <div>
                            <i class="fa-solid fa-arrow-right-to-bracket nav_icon"></i>
                            <div class="nav_icon">
                                Sign-in
                            </div>
                        </div>
                    </a>
                </div>
                <div>
                    <a href="{% url 'account_signup' %}" type="text/html" aria-label="sign-up">
                        <div>
                            <i class="fa-solid fa-user-plus nav_icon"></i>
                            <div class="nav_icon">
                                Sign-up
                            </div>
                        </div>
                    </a>
                </div>
            {% else %}
                <div>
                    <a href="{% url 'account_logout' %}" type="text/html" aria-label="sign-out">
                        <div>
                            <i class="fa-solid fa-right-from-bracket nav_icon"></i>
                            <div class="nav_icon">
                                Sign-out
                            </div>
                        </div>
                    </a>
                </div>
            {% endif %}
                
            <div class="more_menu_button" role="button" aria-haspopup="menu" aria-expanded="false" aria-controls="more_menu" tabindex="0">
                <i class="fa-solid fa-bars nav_icon"></i>
                <div class="nav_icon">
                    More
                </div>
            </div>
            <div id="more_menu_container">
                <div id="more_menu" role="menu" tabindex="0">
                    <div>
                        <span tabindex="0" class="more_menu_button" aria-label="close menu" role="button"><i class="fa-solid fa-xmark"></i> </span> 
                    </div>
                    <div id="menu_items_container">
                        {% block more_menu_items%}{% endblock %}
                        <div role="menuitem" class="menu_item">
                            <a href="{% url 'landing_page:terms_view' %}" type="text/html"><b>T & C</b></a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main>
        {% block main %}{% endblock %}
    </main>
    <footer>
        <div id="site_navigation">
            <p tabindex="0" role="button" id="back_to_top"><u>Back to top</u></p>
        </div>
        <div id="contact_us">
            <p><strong>Contact Us:</strong></p>
            <address>Email: eventabasehost@gmail.com</address>
        </div>
    </footer>
    <script src="https://kit.fontawesome.com/498cc55193.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
</body>
</html>

templates/base_modal.html
<div class="modal_container" tabindex="0" {% if first_login and modal == 'edit_profile_modal' %}style="display:block"{% endif %}>
    <div id="{{modal}}" class="modal" role="dialog" aria-modal="true" tabindex="0" aria-label="{{modal}}">
        <div>
                <div class="close_button" {% if first_login and modal == 'edit_profile_modal' %} style="visibility:hidden"{% endif %}>
                    <span tabindex="0" aria-label="close modal" role="button"><i class="fa-solid fa-xmark"></i> </span> 
                </div>
            <h2>{% block modal_title %}Modal{% endblock %}</h2>
        </div>
        {% block main %}
        {% endblock %}
        <div class="modal_buttons_container">
            <button class='modal_button' type="button" name="{{button1_name}}">{{button1_name|title}}</button>
            {% if button2_name %}
                {% if not first_login or modal != 'edit_profile_modal'%}
                    <button class="modal_button" type="button" name="{{button2_name}}">{{button2_name|title}}</button>
                {% endif %}  
            {% endif %}
        </div>
    </div>
</div>